default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: new
  port: 5432

development:
  <<: *default
  database: greeting_db
  host: localhost
  username: postgres
  password: new
  port: 5432

test:
  <<: *default
  database: greeting_db
  username: postgres
  password: new
  host: localhost
  port: 5432

production:
  <<: *default
  database: greeting_db
  username: postgres
  host: localhost
  password: new
  port: 5432
